name: Postman Collection Run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest
    name: Run Notifications Tests
    steps:
      - uses: actions/checkout@v4

      - name: Install and Run Postman Tests
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          curl -o- "https://dl-cli.pstmn.io/install.sh" | sh
          export PATH="$HOME/.local/share/postman-cli:$PATH"
          postman login --with-api-key "$POSTMAN_API_KEY"
          postman collection run "52238111-8404586c-4aa9-4f1a-9708-983b6319fb98" \
            --environment "52983738-8d7e1e9c-ae6e-4cc1-acc2-b33241a0132b" \
            --verbose